In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.model_selection import train_test_split

In [2]:
import tensorflow as tf
from tensorflow.keras.preprocessing import image

In [3]:
train = pd.read_csv('train_resampled.csv')

In [4]:
train.shape

(4704, 9)

In [5]:
img_dir = r"D:\data\Projects\notebooks\RetinaAI\train_resampled\\"

#### Alle auf einmal in Liste und Array

#### Save memory with multiple lists

#### Save memory with hdf5

In [6]:
import sys
import glob
import h5py
import cv2

In [ ]:
IMG_WIDTH = 512
IMG_HEIGHT = 512

h5file = 'import_images.h5'

nfiles = len(glob.glob(img_dir))
print(f'count of image files nfiles={nfiles}')

# resize all images and load into a single dataset
with h5py.File(h5file,'w') as  h5f:
    img_ds = h5f.create_dataset('images',shape=(nfiles, IMG_WIDTH, IMG_HEIGHT,3), dtype=int)
    for cnt, ifile in enumerate(glob.iglob('./*.ppm')) :
        img = cv2.imread(ifile, cv2.IMREAD_COLOR)
        # or use cv2.IMREAD_GRAYSCALE, cv2.IMREAD_UNCHANGED
        img_resize = cv2.resize( img, (IMG_WIDTH, IMG_HEIGHT) )
        img_ds[cnt:cnt+1:,:,:] = img_resize

In [12]:
IMG_WIDTH = 512
IMG_HEIGHT = 512

In [11]:
h5file = 'import_images.h5'
nfiles = len(glob.glob('D:/data/Projects/notebooks/RetinaAI/train_resampled/*.jpg'))
print(f'Count of image files nfiles = {nfiles}')

Count of image files nfiles = 4704


In [ ]:
with h5py.File(h5file,'w') as  h5f:
    img_ds = h5f.create_dataset('images',shape=(nfiles, IMG_WIDTH, IMG_HEIGHT,3), dtype=int)
    for cnt, ifile in enumerate(glob.iglob('D:/data/Projects/notebooks/RetinaAI/train_resampled/*.jpg')) :
        img = cv2.imread(ifile, cv2.IMREAD_COLOR)
        # or use cv2.IMREAD_GRAYSCALE, cv2.IMREAD_UNCHANGED
        img_resize = cv2.resize( img, (IMG_WIDTH, IMG_HEIGHT) )
        img_ds[cnt:cnt+1:,:,:] = img_resize

In [ ]:
with h5py.File(h5file,'w') as h5f:
    img_ds = h5f.create_dataset('images',shape=(nfiles, IMG_WIDTH, IMG_HEIGHT,3), dtype=int)
    for i in tqdm(range(train.shape[0])):
    img = image.load_img(img_dir+train['filename'][i])
    img = image.img_to_array(img)
    img = img/255

### Save and Load npz file

In [ ]:
from numpy import savez_compressed

In [ ]:
savez_compressed('data.npz', data)

In [13]:
from numpy import load

In [14]:
# load dict of arrays
dict_data = load('data.npz')
# extract the first array
data = dict_data['arr_0']
# print the array
print(data)

[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0

### Check Images

In [ ]:
# No of images, height, width, depth
X.shape

In [ ]:
# Pixel intensity
X[300].min(), X[300].max(), X[300].mean()

In [ ]:
X[300].shape, X[300].size

In [ ]:
X[300][100][200]

In [ ]:
plt.imshow(X[300])

In [ ]:
y = np.array(train.drop(['filename', 'new'], axis=1))
y.shape

In [ ]:
y

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2, test_size=0.1)